name: "CI-CIS  Validation  Action"
description: "Worklow de validation des exemples CI-SIS"
inputs:
  repo:
    description: "Chemin d'accés au repertoire des exemples"
    required: true
  except:
    description: "Répertoires à éviter"
    default: Not Specified
runs:
  using: "composite"
  steps:

      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' 

      - name: Pip upgrade
        shell: bash   
        run : pip install --upgrade pip

      - name: Pip hl7apy
        shell: bash   
        run : pip install hl7apy

      - name: Install requests
        shell: bash   
        run : pip install requests

      - name: Install lxml
        shell: bash   
        run : pip install lxml

      - name: Install glob
        shell: bash   
        run : pip install glob2
        


  
      - name: Run script validation      
        shell: bash   
        continue-on-error: true
        run : |
              python ${{ github.action_path }}/tools/validate.py '${{ github.action_path }}' '${{ inputs.repo}}' './rapport.html' '${{ inputs.except}}'
              echo "# Rapport de validation sur les exemples" >> $GITHUB_STEP_SUMMARY
              cat ./rapport.html  | tr -d "\n\t" >> $GITHUB_STEP_SUMMARY

       




branding:
  icon: 'check'
  color: 'blue'

          
